# 启用插件
enable: true

# 插件前缀
prefix: "&b[区块漏斗]"

# 活塞推出物品后收集
piston: true
# 生物死亡掉落物品后收集
entity: true
# 方块被破坏后收集
block: true
# 作物生长后收集
grow: true
# 爆炸破坏方块后收集
explode: true

# 关闭区块漏斗世界
disable-world:
  - world_nether
  - world_the_end

# 限制漏斗放置最大数量
chunk: true
# 一个区块最大漏斗上限
limit: 32
# 在一个方块被破坏多久之后检测
delay: 30

# 限制红石及红石火把放置最大数量
redstone: true
# 一个区块最大红石及红石火把上限
redstone-limit: 128

# 漏斗物品过滤器 (支持 1.21.9+)
# 漏斗周围放展示架允许让此漏斗只允许展示物品
hopper-filter: false